/**
 * Download and encode farming images as base64 for WhatsApp Flows.
 * WhatsApp Flows requires base64 images (JPEG/PNG) — URLs do not render.
 *
 * Usage: npm run encode:images
 * Output: src/assets/images.ts (auto-generated, do not edit manually)
 */
import * as https from 'https';
import * as fs from 'fs';
import * as path from 'path';

interface ImageDef {
  key: string;
  url: string;
  dest: string;
}

function download(url: string, dest: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const file = fs.createWriteStream(dest);
    function get(u: string) {
      https.get(u, (res) => {
        if (res.statusCode && [301, 302, 303, 307].includes(res.statusCode) && res.headers.location) {
          file.destroy();
          get(res.headers.location);
          return;
        }
        res.pipe(file);
        file.on('finish', () => { file.close(); resolve(dest); });
      }).on('error', (err) => reject(err));
    }
    get(url);
  });
}

const IMAGES: ImageDef[] = [
  { key: 'FARM_HERO_IMAGE', url: 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=400&h=250&fit=crop&fm=jpg&q=70', dest: '/tmp/farm_hero.jpg' },
  { key: 'CROP_FIELD_IMAGE', url: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400&h=250&fit=crop&fm=jpg&q=70', dest: '/tmp/crop_field.jpg' },
  { key: 'HARVEST_IMAGE', url: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400&h=250&fit=crop&fm=jpg&q=70', dest: '/tmp/harvest.jpg' },
  { key: 'FARMER_IMAGE', url: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=400&h=250&fit=crop&fm=jpg&q=70', dest: '/tmp/farmer.jpg' },
];

const CROP_IMAGES: Record<string, string> = {
  wheat:     'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=80&h=80&fit=crop&fm=jpg&q=60',
  paddy:     'https://images.unsplash.com/photo-1605000797499-95a51c5269ae?w=80&h=80&fit=crop&fm=jpg&q=60',
  cotton:    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=80&h=80&fit=crop&fm=jpg&q=60',
  sugarcane: 'https://images.unsplash.com/photo-1528825871115-3581a5387919?w=80&h=80&fit=crop&fm=jpg&q=60',
  chilli:    'https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=80&h=80&fit=crop&fm=jpg&q=60',
  maize:     'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=80&h=80&fit=crop&fm=jpg&q=60',
  tomato:    'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=80&h=80&fit=crop&fm=jpg&q=60',
  potato:    'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=80&h=80&fit=crop&fm=jpg&q=60',
  soybean:   'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=80&h=80&fit=crop&fm=jpg&q=60',
  bajra:     'https://images.unsplash.com/photo-1602738328654-51ab2ae6c4ff?w=80&h=80&fit=crop&fm=jpg&q=60',
  banana:    'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=80&h=80&fit=crop&fm=jpg&q=60',
};

const run = async () => {
  console.log('Downloading farming images...');

  // Main images
  await Promise.all(IMAGES.map((img) =>
    download(img.url, img.dest)
      .then(() => console.log(img.key, ':', Math.round(fs.statSync(img.dest).size / 1024) + 'KB'))
      .catch((e) => console.warn('Failed to download', img.key, e.message))
  ));

  // Crop icons
  const cropEntries: string[] = [];
  for (const [id, url] of Object.entries(CROP_IMAGES)) {
    const dest = `/tmp/crop_${id}.jpg`;
    try {
      await download(url, dest);
      const b64 = fs.readFileSync(dest).toString('base64');
      cropEntries.push(`  ${id}: '${b64}'`);
      console.log('crop.' + id, ':', Math.round(b64.length / 1024) + 'KB b64');
    } catch (e) {
      console.warn('Failed crop image for', id);
      cropEntries.push(`  ${id}: ''  // download failed — add manually`);
    }
  }

  const lines: string[] = [
    '/**',
    ' * Base64-encoded farming images for WhatsApp Flow JSON.',
    ' * WhatsApp Flows requires base64 images (JPEG/PNG) — URLs do not render.',
    ' * Auto-generated by: npm run encode:images — do not edit manually.',
    ' */',
    '',
  ];

  for (const img of IMAGES) {
    try {
      const b64 = fs.readFileSync(img.dest).toString('base64');
      lines.push(`export const ${img.key} = '${b64}';`);
      lines.push('');
    } catch {
      lines.push(`export const ${img.key} = '';  // download failed`);
      lines.push('');
    }
  }

  lines.push('export const CROP_IMAGES: Record<string, string> = {');
  lines.push(...cropEntries.map((e) => e + ','));
  // fill in aliases for crops without dedicated images
  const extra = ['jowar', 'mustard', 'groundnut', 'castor', 'ragi', 'jute', 'coconut', 'rubber', 'pepper', 'lychee'];
  for (const id of extra) {
    lines.push(`  ${id}: '',  // add base64 image manually or leave empty`);
  }
  lines.push('};');

  const outPath = path.join(__dirname, '../src/assets/images.ts');
  fs.writeFileSync(outPath, lines.join('\n'));
  console.log('');
  console.log('Written:', outPath, Math.round(fs.statSync(outPath).size / 1024) + 'KB');
};

run().catch(console.error);
